 USE ECOMMERCE;

 -- Inserindo dados na tabela CLIENTE
INSERT INTO CLIENTE (FNAME, MINIT, LNAME, CPF, ENDERECO) 
VALUES 
('João', 'A', 'Silva', '12345678901', 'Rua A, 123'),
('Maria', 'B', 'Oliveira', '09876543210', 'Rua B, 456');

-- Inserindo dados na tabela PRODUTO
INSERT INTO PRODUTO (PNAME, CLASSIFICACAO_KIDS, CATEGORIA, RATING, SIZE) 
VALUES 
('Celular', FALSE, 'ELETRONICO', 4.5, 'M'),
('Camiseta', TRUE, 'ROUPAS', 4.0, 'G'),
('Boneca', TRUE, 'BRINQUEDOS', 5.0, 'P');

-- Inserindo dados na tabela FORNECEDOR
INSERT INTO FORNECEDOR (RAZAOSOCIAL, CNPJ, CONTATO) 
VALUES 
('Fornecedor A', '12345678000190', '11987654321'),
('Fornecedor B', '98765432000199', '11912345678');

-- Inserindo dados na tabela VENDEDOR
INSERT INTO VENDEDOR (NOMESOCIAL, NOMEABSTRATO, CNPJ, CPF, LOCALIZACAO, CONTATO) 
VALUES 
('Vendedor A', 'Abstrato A', '12345678000190', '123456789', 'São Paulo', '11987654321'),
('Vendedor B', 'Abstrato B', '98765432000199', '098765432', 'Rio de Janeiro', '11912345678');

-- Inserindo dados na tabela ESTOQUE
INSERT INTO ESTOQUE (QUANTIDADE, LOCALESTOQUE) 
VALUES 
(100, 'São Paulo'),
(50, 'Rio de Janeiro');

-- Inserindo dados na tabela PEDIDO
INSERT INTO PEDIDO (PRODUTOID_PEDIDO, CLIENTEID_PEDIDO, PEDIDOSTATUS, PEDIDODESCRICAO, VALORFRETE, PAGAMENTO) 
VALUES 
(1, 1, 'PROCESSANDO', 'Compra de celular', 15.0, 'CARTÃO'),
(2, 2, 'CONFIRMADO', 'Compra de camiseta', 10.0, 'DINHEIRO');

-- Inserindo dados na tabela PRODUTOPEDIDO
INSERT INTO PRODUTOPEDIDO (IDPPRODUTO, IDPPEDIDO, PQUANTIDADE, PSTATUS) 
VALUES 
(1, 1, 2, 'DISPONÍVEL'),
(2, 2, 1, 'DISPONÍVEL');

-- Inserindo dados na tabela PRODUTOVENDEDOR
INSERT INTO PRODUTOVENDEDOR (IDPVENDEDOR, IDPPRODUTO, QUANTIDADE) 
VALUES 
(1, 1, 10),
(2, 2, 5);

-- Inserindo dados na tabela ESTOQUELOCALIZACAO
INSERT INTO ESTOQUELOCALIZACAO (IDLPRODUTO, IDLESTOQUE, LOCALIZACAO) 
VALUES 
(1, 1, 'A1'),
(2, 2, 'B2');

-- Inserindo dados na tabela PAGAMENTO
INSERT INTO PAGAMENTO (IDPEDIDO, TIPO_PAGAMENTO, TIPO_CARTAO, VALOR_TOTAL, DATA_PAGAMENTO) 
VALUES 
(1, 'CARTÃO', 'DÉBITO', 1500.00, CURDATE()),
(2, 'DINHEIRO', NULL, 50.00, CURDATE());

SHOW TABLES;
SELECT * FROM PRODUTO;