USE LITORAL;

-- ALTERAÇAO DE COMMIT
SET AUTOCOMMIT=0;
-- SAVEPOINT 
SAVEPOINT POINT1;
-- CRIANDO UM UPDATE ERRADO
UPDATE DESTINO SET NOME = "ILHA DO MAR";
-- ULTILIZANDO O ROLLBACK
ROLLBACK TO SAVEPOINT POINT1;
-- GRAVANDO AS ALTERAÇÕES 
COMMIT;
-- CRIANDO UM 2 SAVEPOINT
SAVEPOINT POINT2;
-- CRIANDO FUNÇÕES NO BANCO DE DADOS, EM ESPECÍFICO DAS 30% DE DESCONTO EM DETERMINADAS DATAS 
CREATE FUNCTION FN_DESC(X DECIMAL(5,2), Y INT) 
RETURNS DECIMAL(5,2) 
RETURN ((X*Y)*0.7); 